---
title: "Logicals"
author: "Peter Menzies"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Taking a look at `starwars`

- `include =` show or hide everything
- `echo =` show or hide code

```{r, include = FALSE}
summary(starwars)

head(starwars)

dim(starwars)
```

```{r, eval = FALSE}
ggplot(data = starwars, aes(x = height, y = mass)) +
  geom_point(aes(color = species))
```

## Find the mean variance and sd of character height

```{r}
#default in mean function is NA output if there are missing values
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_mean

# using similar naming, find:
# variance of character height (var())
# sd of character height (sd())

sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_var

sw_height_sd <- sd(starwars$height, na.rm = TRUE)
sw_height_sd
```

Mean character height is `r round(sw_height_mean)` cm, with a SD of `r round(sw_height_sd)` cm.


## Logical Expressions

```{r}
5 < 10
```
```{r}
10 <= 11
```

```{r}
tarantulas <- c(1,3,7,10,15)

tarantulas > 5
```

## Logical operators:

- `!`
- `&`
- `|`

```{r}
3 < 1 | 8 > 2

6 < 10 & 5 < 1

7 != 11

0 == FALSE
1 == TRUE
```
